### ISSUE TITLE
it breaks Jest tests

### ISSUE THREAD

**Issue by ondrejrohon** [quangbuule/extract-hoc#3]
Hi,

I added this plugin to solve this issue: https://github.com/gaearon/react-hot-loader/issues/650 but suddenly it broke my tests. I get a lot of errors like this:
```
SyntaxError: Identifier '_languageProp_arg' has already been declared

      at Runtime._execModule (node_modules/jest-runtime/build/index.js:520:13)
      at Object.<anonymous> (src/helpers/index.js:1:637)
      at Object.<anonymous> (src/helpers/__tests__/updateMarkers.js:2:9)
          at Generator.next (<anonymous>)
          at new Promise (<anonymous>)
      at handle (node_modules/worker-farm/lib/child/index.js:44:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:51:3)
      at emitTwo (events.js:126:13)
      at process.emit (events.js:214:7)
      at emit (internal/child_process.js:772:12)
      at _combinedTickCallback (internal/process/next_tick.js:141:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

It is ejected create-react-app. I added babel config to package.json:
```
"babel": {
    "presets": [
      "react-app",
      "stage-1"
    ],
    "plugins": [
      "extract-hoc/babel",
      "react-hot-loader/babel"
    ]
  },
```

Any ideas what might be wrong? Thanks.

**Comment by quangbuule** [comment]
I think that my plugin and react-hot-loader should be used for development only, I mean you shouldn't include those plugins for test. Related babel doc is here: 
https://babeljs.io/docs/usage/babelrc/#env-option

**Comment by ondrejrohon** [comment]
Correct, I figured it out literally 2 minutes ago. Thanks :)
